controller_list:
  - name: fake_arm_controller
    joints:
      - axis_j1
      - axis_j2
      - axis_j3
      - axis_j4
      - axis_j5
      - axis_j6
  - name: fake_gripper_controller
    joints:
      - axis_j6